from .exceptions import (AuthFailed)

assert AuthFailed
