from .exceptions.exceptions import (AuthFailed)

assert AuthFailed